import yfinance as yf
import streamlit as st
import pandas as pd

BIST_HISSELER = [
    "ACSEL","ADEL","ADESE","AEFES","AFYON","AGESA","AGHOL","AGYO","AKBNK","AKCNS",
    "AKENR","AKFEN","AKFGY","AKFYE","AKGRT","AKMGY","AKSA","AKSEN","AKSGY","AKSUE",
    "AKTAE","ALARK","ALBRK","ALFAS","ALGYO","ALKA","ALKIM","ALKLC","ALMAD","ALTNY",
    "ALVES","ANELE","ANGEN","ANHYT","ANSGR","ARASE","ARCLK","ARDYZ","ARENA","ARFYO",
    "ARSAN","ARTMS","ASELS","ASGYO","ASTOR","ASUZU","ATAGY","ATAKP","ATATP","ATEKS",
    "ATLAS","ATSYH","AVGYO","AVHOL","AVISA","AVOD","AVTUR","AYCES","AYDEM","AYES",
    "AYGAZ","AZTEK","BAGFS","BAKAB","BALAT","BANVT","BARMA","BASCM","BASGZ","BERA",
    "BEYAZ","BFREN","BIGCH","BIMAS","BIOEN","BIZIM","BJKAS","BLCYT","BMEKS","BMSCH",
    "BNTAS","BOBET","BOSSA","BRISA","BRKSN","BRKVY","BRMEN","BRSAN","BRYAT","BSOKE",
    "BTCIM","BUCIM","BURCE","BURVA","BVSAN","CCOLA","CELHA","CEMAS","CEMTS","CEOEM",
    "CIMSA","CLEBI","CMBTN","CMENT","COFSA","CRFSA","CUSAN","CVKMD","CWENE","DAGHL",
    "DAGI","DAPGM","DARDL","DENGE","DERHL","DESA","DESPC","DEVA","DGATE","DGGYO",
    "DGNMO","DITAS","DJIST","DMSAS","DNISI","DOAS","DOBUR","DOCO","DOGUB","DOHOL",
    "DOKTA","DURDO","DYOBY","DZGYO","ECILC","ECZYT","EDIP","EFORC","EGEEN","EGGUB",
    "EGPRO","EGSER","EKGYO","EKSUN","ELITE","EMKEL","EMNIS","ENJSA","ENKAI","ENSRI",
    "EPLAS","ERCB","EREGL","ERSU","ESCAR","ESCOM","ESEN","ETILR","ETYAT","EUHOL",
    "EUKYO","EUPWR","EVKUR","EYGYO","FADE","FENER","FMIZP","FONET","FORMT","FORTE",
    "FRIGO","FROTO","FZLGY","GARAN","GARFA","GEDIK","GEDZA","GENTS","GEREL","GESAN",
    "GIPTA","GLBMD","GLCVY","GLYHO","GMTAS","GOKNR","GOLTS","GOODY","GOZDE","GRSEL",
    "GRTRK","GSDDE","GSDHO","GSRAY","GUBRF","GWIND","GZNMI","HALKB","HATEK","HEKTS",
    "HKTM","HLGYO","HRKET","HTTBT","HUBVC","HUNER","HURGZ","ICBCT","ICUGS","IDEAS",
    "IEYHO","IHAAS","IHEVA","IHGZT","IHLAS","IHLGM","IHYAY","IMASM","INDES","INFO",
    "INGRM","INTEM","INVEO","IPEKE","IPMAT","ISATR","ISBIR","ISCTR","ISYAT","ITTFH",
    "IZENR","IZFAS","IZINV","IZMDC","JANTS","KAPLM","KAREL","KARSN","KARTN","KATMR",
    "KAYSE","KBORU","KCAER","KCHOL","KERVT","KFEIN","KGYO","KIMMR","KLGYO","KLKIM",
    "KLMSN","KLRHO","KLSER","KMPCT","KMPUR","KNFRT","KONYA","KORDS","KOZAA","KOZAL",
    "KRDMA","KRDMB","KRDMD","KRGYO","KRPLS","KRSTL","KRTEK","KRVGD","KSTUR","KTLEV",
    "KUTPO","KUVVA","KUYAS","KVKK","KZGYO","LIDER","LIDFA","LILAK","LINK","LKMNH",
    "LOGO","LRSHO","LUKSK","MAALT","MACKO","MAGEN","MAKIM","MAKTK","MANAS","MARBL",
    "MAVI","MEDTR","MEGAP","MEKAG","METEM","METRO","METUR","MHRGY","MIATK","MIPAZ",
    "MNDRS","MNDTR","MOBTL","MOGAN","MPARK","MRGYO","MRSHL","MSGYO","MTRKS","MZHLD",
    "NATEN","NETAS","NIBAS","NTGAZ","NTHOL","NUGYO","NUHCM","OBAMS","OBASE",
    "ODAS","ODINE","OFSYM","ONCSM","ORCAY","ORGE","ORMA","OSMEN","OSTIM","OTKAR",
    "OTTO","OYAKC","OYAYO","OYLUM","OZGYO","OZKGY","PAGYO","PAMEL","PAPIL","PARSN",
    "PASEU","PCILT","PEHOL","PEKGY","PENGD","PENTA","PETKM","PETUN","PGSUS","PINSU",
    "PKART","PKENT","PLTUR","PNLSN","POLHO","POLTK","PRDGS","PRKAB","PRKME","PRZMA",
    "PSDTC","PSGYO","QNBFB","QNBFL","RAYSG","RHEAG","RODRG","ROYAL","RTALB","RYGYO",
    "SAFKR","SAHOL","SAMAT","SANEL","SANFM","SANKO","SARKY","SASA","SAYAS","SDTTR",
    "SEGMN","SEGYO","SEKFK","SEKUR","SELEC","SELGD","SELVA","SEYKM","SILVR","SISE",
    "SKBNK","SKYLP","SLCTR","SMART","SMRTG","SNGYO","SNICA","SOKM","SONME","SOROR",
    "SRVGY","SUMAS","SUNEK","SUWEN","SZGYO","TARKM","TATEN","TAVHL","TBORG","TCELL",
    "TDGYO","TEKTU","TERA","TETMT","THYAO","TKFEN","TKNSA","TMSN","TNZTP","TOASO",
    "TRCAS","TRGYO","TRILC","TSGYO","TSKB","TSPOR","TTKOM","TTRAK","TUCLK","TUKAS",
    "TUPRS","TUREX","TURGG","TURSG","ULUUN","ULKER","ULUFA","UNLU","USAK","USDTR",
    "VAKBN","VAKFN","VAKKO","VANGD","VAROL","VERUS","VESBE","VESTL","VKFYO","VKGYO",
    "VKING","YATAS","YAYLA","YBTAS","YGYO","YIGIT","YKSLN","YUNSA","YYLGD","ZEDUR",
    "ZRGYO","ZOREN","ZORLU"
]

@st.cache_data(ttl=300)
def get_stock_data(ticker, period="1y"):
    df = yf.download(f"{ticker}.IS", period=period, auto_adjust=True)
    # yfinance yeni sürümlerinde MultiIndex döndürüyor, düzleştir
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df

def get_stock_info(ticker):
    stock = yf.Ticker(f"{ticker}.IS")
    return stock.info

def get_bist_hisseler():
    return sorted(BIST_HISSELER)
